### ISSUE TITLE
GUI breaks if template file is not correct

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#100]
I understand that using such a template file is not the goal of BIDScoin. However, I submit my observation that if the template is not correct, the gui breaks.

My template file:
```
Options: 
  bidscoin:
    version: 3.6.2
  plugins:
    dcm2bidsmap: {}

DICOM:

  subject: <<SourceFilePath>>
  session: <<SourceFilePath>>

  func:
  - provenance:
    attributes: &func_dicomattr
    bids: &func_bidsattr
      suffix: bold
```
I execute `bidsmapper` with the `-t` option to pass the template file. Then, all images are assigned `extra_data` data type. If I change that type to `func`, which is defined in the template, the gui works. If, however, I change the data type to `fmap`, which is available in the drop-down list in the gui but not defined in the template, the gui breaks and closes with an error:
```
...
2021-07-16 18:17:27 - INFO | User has changed the BIDS data type from 'func' to 'fmap' for ...
2021-07-16 18:17:27 - WARNING | 'fmap' run with suffix_idx '0' not found in bidsmap['DICOM']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidseditor.py", line 1242, in datatype_dropdown_change
    self.change_run(0)
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidseditor.py", line 1233, in change_run
    self.reset(refresh=True)
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidseditor.py", line 1303, in reset
    self.refresh_bidsname()
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidseditor.py", line 1256, in refresh_bidsname
    bidsname = (Path(self.target_datatype)/bids.get_bidsname(self.subid, self.sesid, self.target_run)).with_suffix('.*')
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bids.py", line 1172, in get_bidsname
    bidsname = f"{bidsname}{add_prefix('_', run['bids']['suffix'])}"            # And end with the suffix
KeyError: 'suffix'
Aborted
```

**Comment by marcelzwiers** [comment]
I think I know what happened, if you change the datatype or suffix, then the editor considers it to be a new that it then takes from the template. If the suffix is not in the template bidsmap (which is what your error message is probably saying) then it crashes. I can see if I can more elegantly handle this exception.
