### ISSUE TITLE
bidscoin --download .  results in "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by yarikoptic** [Donders-Institute/bidscoin#113]
**Describe the bug**

```shell
$>  bidscoin --download .
2021-11-05 16:53:01 - INFO | Downloading the tutorial dataset...
2021-11-05 16:53:14 - INFO | Unzipping the downloaded data in: /tmp/bidscoin-try
2021-11-05 16:53:17 - INFO | --------- Testing the BIDScoin tools and settings ---------
2021-11-05 16:53:17 - ERROR | expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/yoh/proj/bids/bidscoin/venvs/dev3/bin/bidscoin", line 33, in <module>
    sys.exit(load_entry_point('bidscoin', 'console_scripts', 'bidscoin')())
  File "/home/yoh/proj/bids/bidscoin/bidscoin/bidscoin.py", line 442, in main
    test_bidscoin(bidsmapfile=args.test)
  File "/home/yoh/proj/bids/bidscoin/bidscoin/bidscoin.py", line 369, in test_bidscoin
    if testplugins and 'plugins' in options:
TypeError: argument of type 'NoneType' is not iterable
bidscoin --download .  4.21s user 2.03s system 36% cpu 17.210 total
```

**Software version**

```
$> bidscoin --version
BIDS-version:		1.6.0
BIDScoin-version:	3.7.0-dev, NB: Your BIDScoin version is NOT up-to-date: 3.7.0-dev -> 3.6.3

$> uname -a
Linux lena 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

```

straight from current master: 

```
$> git describe
fatal: No annotated tags can describe 'af8d66ff7ebd1801c6cc0ff55542a99ee9cacecb'.
However, there were unannotated tags: try --tags.

$> git describe --tags
3.6.2-190-gaf8d66f
```

**Comment by marcelzwiers** [comment]
Thanks for reporting: a test was accidentally (and wrongly) performed after downloading the data. Now fixed
