### ISSUE TITLE
Phys2bids cannot find `pymatreader` when assessing an EEG mat-file

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#117]
**Describe the bug**
The phys2bids crashes / misses a library when it tries to assess whether it can read an EEG mat-file

**To reproduce**
In the subject folders, there were both MRI and EEG data (and some other modalities), and when running the bidsmapper an error was raised due to phys2bids trying to read the EEG data: 

```
Reading the file /project/3022035.04/raw_MRStest/sub-220203100/ses-1/eeg/eventList.mat                     
Traceback (most recent call last):                                                                                                      
  File "/opt/bidscoin/dev/bidscoin/bidsmapper.py", line 231, in <module>
    main()
  File "/opt/bidscoin/dev/bidscoin/bidsmapper.py", line 218, in main
    bidsmapper(rawfolder    = args.sourcefolder,
  File "/opt/bidscoin/dev/bidscoin/bidsmapper.py", line 134, in bidsmapper
    module.bidsmapper_plugin(session, bidsmap_new, bidsmap_old, template, store)
  File "/opt/bidscoin/dev/bidscoin/plugins/phys2bidscoin.py", line 146, in bidsmapper_plugin
    run, _ = bids.get_matching_run(datasource, template)
  File "/opt/bidscoin/dev/bidscoin/bids.py", line 1393, in get_matching_run
    sourcevalue = datasource.attributes(attrkey, validregexp=True)
  File "/opt/bidscoin/dev/bidscoin/bids.py", line 145, in attributes
    attributeval = module.get_attribute(self.dataformat, self.path, attributekey, options)
  File "/opt/bidscoin/dev/bidscoin/plugins/phys2bidscoin.py", line 104, in get_attribute
    phys_info = phys2bids_cache(sourcefile)
  File "/opt/bidscoin/dev/bidscoin/plugins/phys2bidscoin.py", line 81, in phys2bids_cache
    return phys2bids(str(sourcefile), info=True)
  File "/opt/bidscoin/lib/python3.8/site-packages/phys2bids/phys2bids.py", line 229, in phys2bids
    phys_in = load_mat(infile, chtrig)
  File "/opt/bidscoin/lib/python3.8/site-packages/phys2bids/io.py", line 372, in load_mat
    from pymatreader import read_mat
ModuleNotFoundError: No module named 'pymatreader'
```

**Software version**
 - BIDScoin version 3.7-dev
 - OS Linux

**Comment by marcelzwiers** [comment]
@smoia I presume this has to do with the (minimal) phys2bids installation, any suggestions?

**Comment by smoia** [comment]
Hello @marcelzwiers ! We currently do not support EEG conversion - but if it works he great news!
I guess the issue is related to the setup indeed. Let me see if I can do a quick fix.

**Comment by smoia** [comment]
I checked your setup, and if you install correctly phys2bidscoin, one of the dependencies you specify is pymatreader (at least that's what I understand from [here](https://github.com/Donders-Institute/bidscoin/blob/4cacb11a45e11ba9d64b2a39e809567d5c4585c4/setup.py#L16) ).
Could you check that the installation went well?

**Comment by marcelzwiers** [comment]
Sorry, my mistake :-)
