### ISSUE TITLE
Error when installing from GitHub: "fatal: No url found for submodule path 'tests/testdata' in .gitmodules"

### ISSUE THREAD

**Issue by Catyre** [Donders-Institute/bidscoin#142]
**Describe the bug**
Sorry to keep being the bearer of bad news, but I am now having a separate error from today's earlier one when trying to install BIDScoin from GitHub.

After some research into similar but not exact versions of this problem (see [here](https://stackoverflow.com/questions/59508121/no-url-found-for-submodule-path-in-gitmodules-error-in-azure-devops-build)), it seems that the problem is that `tests/testdata` is a submodule that either has an incorrect URL or no URL at all.  However, since this is a part of the git repository I am trying to clone, I can't make the suggested changes myself.  Unless I'm misunderstanding the SO answer.

**To reproduce**
1. Run `pip install --upgrade git+https://github.com/Donders-Institute/bidscoin` OR `pip install --upgrade git+git://github.com/Donders-Institute/bidscoin`

**Expected behavior**
BIDScoin downloads successfully with the latest development version

**Full Error Log**
```
2022-06-14T17:36:14,271 Using pip 21.2.4 from /Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip (python 3.9)
2022-06-14T17:36:14,272 Non-user install because site-packages writeable
2022-06-14T17:36:14,494 Created temporary directory: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-ephem-wheel-cache-bgs3op65
2022-06-14T17:36:14,494 Created temporary directory: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-tracker-6fk_0641
2022-06-14T17:36:14,495 Initialized build tracking at /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-tracker-6fk_0641
2022-06-14T17:36:14,495 Created build tracker: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-tracker-6fk_0641
2022-06-14T17:36:14,495 Entered build tracker: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-tracker-6fk_0641
2022-06-14T17:36:14,495 Created temporary directory: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-install-_n0nl6h2
2022-06-14T17:36:14,504 Collecting git+https://github.com/Donders-Institute/bidscoin
2022-06-14T17:36:14,505   Created temporary directory: /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-build-4m07iuvm
2022-06-14T17:36:14,505   Cloning https://github.com/Donders-Institute/bidscoin to /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-build-4m07iuvm
2022-06-14T17:36:14,505   Running command git clone -q https://github.com/Donders-Institute/bidscoin /private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-build-4m07iuvm
2022-06-14T17:36:15,797   Running command git rev-parse HEAD
2022-06-14T17:36:15,813   e3275c76a985e804b880858f97aafa3f121d792a
2022-06-14T17:36:15,813   Resolved https://github.com/Donders-Institute/bidscoin to commit e3275c76a985e804b880858f97aafa3f121d792a
2022-06-14T17:36:15,813   Running command git submodule update --init --recursive -q
2022-06-14T17:36:16,089   fatal: No url found for submodule path 'tests/testdata' in .gitmodules
2022-06-14T17:36:16,090 WARNING: Discarding git+https://github.com/Donders-Institute/bidscoin. Command errored out with exit status 128: git submodule update --init --recursive -q Check the logs for full command output.
2022-06-14T17:36:16,091 ERROR: Command errored out with exit status 128: git submodule update --init --recursive -q Check the logs for full command output.
2022-06-14T17:36:16,091 Exception information:
2022-06-14T17:36:16,091 Traceback (most recent call last):
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
2022-06-14T17:36:16,091     status = self.run(options, args)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
2022-06-14T17:36:16,091     return func(self, options, args)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 315, in run
2022-06-14T17:36:16,091     requirement_set = resolver.resolve(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
2022-06-14T17:36:16,091     collected = self.factory.collect_root_requirements(root_reqs)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 471, in collect_root_requirements
2022-06-14T17:36:16,091     req = self._make_requirement_from_install_req(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 448, in _make_requirement_from_install_req
2022-06-14T17:36:16,091     raise self._build_failures[ireq.link]
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
2022-06-14T17:36:16,091     self._link_candidate_cache[link] = LinkCandidate(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
2022-06-14T17:36:16,091     super().__init__(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2022-06-14T17:36:16,091     self.dist = self._prepare()
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
2022-06-14T17:36:16,091     dist = self._prepare_distribution()
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
2022-06-14T17:36:16,091     return self._factory.preparer.prepare_linked_requirement(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
2022-06-14T17:36:16,091     return self._prepare_linked_requirement(req, parallel_builds)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
2022-06-14T17:36:16,091     local_file = unpack_url(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 208, in unpack_url
2022-06-14T17:36:16,091     unpack_vcs_link(link, location)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 68, in unpack_vcs_link
2022-06-14T17:36:16,091     vcs_backend.unpack(location, url=hide_url(link.url))
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py", line 626, in unpack
2022-06-14T17:36:16,091     self.obtain(location, url=url)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py", line 534, in obtain
2022-06-14T17:36:16,091     self.fetch_new(dest, url, rev_options)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/vcs/git.py", line 291, in fetch_new
2022-06-14T17:36:16,091     self.update_submodules(dest)
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/vcs/git.py", line 470, in update_submodules
2022-06-14T17:36:16,091     cls.run_command(
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py", line 669, in run_command
2022-06-14T17:36:16,091     return call_subprocess(cmd, show_stdout, cwd,
2022-06-14T17:36:16,091   File "/Users/cremocal/opt/anaconda3/envs/CONDA-PSY/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
2022-06-14T17:36:16,091     raise InstallationSubprocessError(proc.returncode, command_desc)
2022-06-14T17:36:16,091 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 128: git submodule update --init --recursive -q Check the logs for full command output.
2022-06-14T17:36:16,200 Removed build tracker: '/private/var/folders/9n/zsm_tkrd1c77pdyx39vcb_nr0000gn/T/pip-req-tracker-6fk_0641'
```

**Software version**
 - BIDScoin version: 3.7.2
 - OS (e.g. Windows, Linux, MacOS): MacOS Monterey

**Comment by Catyre** [comment]
It should be noted that this log is for pip 21.2.4, but the exact error also shows for pip 22.1.2 (the latest version)

**Comment by marcelzwiers** [comment]
Strange. The problem is related to pull request #120, which I commented out in commit b13792eaf9b098510a71674f9af1efe9b3d26952. I have now removed the .gitmodules file completely (since it is not used)
