### ISSUE TITLE
dcm2niix failed to run error 3

### ISSUE THREAD

**Issue by fooms2512** [Donders-Institute/bidscoin#162]
Hi ,

When I define the option in bidsmapper to run the tutorial, I have the following error message:
Failed to run dcm2niix -v error 3: Chris Rorden's dcm2niiX version v1.0.20220720  MSC1916  (64-bit Windows)
v1.0.20220720

I'm trying to use bidscoiner on Windows11 version 22H2
I have installed MRIcroGL and when I launch the same command (dcm2niix -v) in windows terminal I don't receive an error message.

Thanks for helping me,
Fred

**Comment by marcelzwiers** [comment]
Hi Fred, did you provide the fullpath to your dcm2niix-binary in the dcm2niix options (e.g. `"C:\Program Files\MRIcroGL\Resources\dcm2niix"`)?
https://bidscoin.readthedocs.io/en/latest/options.html#dcm2niix2bids-plugin

**Comment by marcelzwiers** [comment]
You can set your dcm2niix-path every time in the bidseditor, or once and for all in the bidsmap template

**Comment by fooms2512** [comment]
Yes I also tried with the path "C:\toolbox\MRIcroGL\Resources\dcm2niix.exe"
The test worked fine but when I run bidscoin after no files are bidsyfied?
![image](https://user-images.githubusercontent.com/63711942/200313859-fb72bf3c-f916-470a-a543-25cda2b07e8d.png)
Here is the output of the error
![image](https://user-images.githubusercontent.com/63711942/200313961-e2f5b4ad-b1c8-432c-b8ca-4ff801566d47.png)

**Comment by marcelzwiers** [comment]
It's a puzzling error, because it actually suggests that a nifti file was produced but not the json file. I need some more logging info to see what's going on. Would you perhaps be willing to share your `/bids/code/bidscoin/bidscoiner.log` file with me?

**Comment by fooms2512** [comment]
This is the content of the log file
2022-11-08 17:40:23 - INFO | 
2022-11-08 17:40:23 - INFO | -------------- START BIDScoiner 3.7.4: BIDS 1.7.0 ------------
2022-11-08 17:40:23 - INFO | >>> bidscoiner sourcefolder=F:\Steven\raw bidsfolder=F:\Steven\bids subjects=None force=False participants=False bidsmap=bidsmap.yaml
2022-11-08 17:40:23 - INFO | Creating dataset description file: F:\Steven\bids\dataset_description.json
2022-11-08 17:40:23 - INFO | Creating a template README file (adjust it to your needs): F:\Steven\bids\README
2022-11-08 17:40:24 - INFO | Reading: F:\Steven\bids\code\bidscoin\bidsmap.yaml
2022-11-08 17:40:25 - INFO | Writing ['mrs/', 'extra_data/'] entries to F:\Steven\bids\.bidsignore
2022-11-08 17:40:25 - INFO | ------------------- Subject 1/1 -------------------
2022-11-08 17:40:25 - INFO | Coining datasources in: F:\Steven\raw\sub-JYG\ses-mri01
2022-11-08 17:40:25 - INFO | Executing plugin: dcm2niix2bids.py
2022-11-08 17:40:25 - INFO | Leaving out: F:\Steven\raw\sub-JYG\ses-mri01\001-AAHead_Scout_64ch-head-coil
2022-11-08 17:40:25 - INFO | Leaving out: F:\Steven\raw\sub-JYG\ses-mri01\002-AAHead_Scout_64ch-head-coil_MPR_sag
2022-11-08 17:40:25 - INFO | Leaving out: F:\Steven\raw\sub-JYG\ses-mri01\003-AAHead_Scout_64ch-head-coil_MPR_cor
2022-11-08 17:40:25 - INFO | Leaving out: F:\Steven\raw\sub-JYG\ses-mri01\004-AAHead_Scout_64ch-head-coil_MPR_tra
2022-11-08 17:40:26 - INFO | Processing: F:\Steven\raw\sub-JYG\ses-mri01\005-ep2d_bold_repos_moco_p2_s3_3mm_64ch
2022-11-08 17:40:26 - INFO | Running: C:	oolbox\MRIcroGL\Resources\dcm2niix.exe -b y -z y -i n -l n -f "sub-JYG_ses-mri01_task-ep2dboldreposmocop2s33mm64ch_run-1_echo-1_bold" -o "F:\Steven\bids\sub-JYG\ses-mri01\func" "F:\Steven\raw\sub-JYG\ses-mri01\005-ep2d_bold_repos_moco_p2_s3_3mm_64ch"
2022-11-08 17:40:26 - INFO | Output:

**Comment by marcelzwiers** [comment]
Mhh, no output from running the dcm2niix command. But are you sure your path is fine? The output above says `oolbox`, which seems to miss part of the string:
`Running: C: oolbox\MRIcroGL\Resources\dcm2niix.exe`

**Comment by marcelzwiers** [comment]
You can directly change it with `bidseditor [your_bids_dir]`

**Comment by fooms2512** [comment]
Hi Marcel,
I have changed the Folder name but now I have an error message linked with pigz.exe:

2022-11-09 07:00:03 - INFO | User has set the 'dcm2niix2bids' option from 'command: C:\Toolbox\MRIcroGL\Resources\dcm2niix' to 'command: C:\Toolbox\MRIcroGL\Resources\dcm2niix.exe'
2022-11-09 07:00:03 - INFO | --------- Testing the 'dcm2niix2bids' plugin ---------
2022-11-09 07:00:03 - INFO | Succesfully imported 'dcm2niix2bids'
2022-11-09 07:00:03 - INFO | Testing the dcm2niix2bids installation:
2022-11-09 07:00:03 - INFO | Running: C:\Toolbox\MRIcroGL\Resources\dcm2niix.exe -v
2022-11-09 07:00:03 - ERROR | Failed to run:
C:\Toolbox\MRIcroGL\Resources\dcm2niix.exe -v
Errorcode 3:
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20211006

I checked and the exe is well located in the same folder. Do I have to define/redifine the path?

**Comment by marcelzwiers** [comment]
The pgiz is just an option to accelerate, not an error (although it is communicated by dcm2niix with an errorcode). You can't (and don't have to) provide the path to pigz, it should be on the path already. If not (as in your case), you can try to install pigz separately? NB: you can run bidscoin fine without pigz...

**Comment by marcelzwiers** [comment]
I discovered that it is the quotation around the entire command string that is causing the problem. For instance, this works:
```
C:"\toolbox\MRIcroGL\Resources\dcm2niix.exe"
```
But strangely enough this doesn't:
```
"C:\toolbox\MRIcroGL\Resources\dcm2niix.exe"
```

**Comment by marcelzwiers** [comment]
Fixed in the next release, thanks for your feedback! :-)

**Comment by Sam54000** [comment]
Hi, I have exactly the same issue and I did everything that was mentioned but nothing.

When I choose an absolute path to the executable I run to this error:
`INFO | Running: C:\Users\Software\MRIcroGL\Resources\dcm2niix.exe -v
ERROR | Failed to run:
C:\Users\Software\MRIcroGL\Resources\dcm2niix.exe -v
Errorcode 3:
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20220720`

I did change the location of the executable to "Program Files" and provided the path to bidsmap_dccn.yaml as either:
`C:\"Program Files"\dcm2niix\dcm2niix.exe`
or
`'C:\"Program Files"\dcm2niix\dcm2niix.exe'`

But I have the same error message. In all previous cases the json file is not generated and induce this error:
`INFO | Output:

Traceback (most recent call last):
  File "C:\Users\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\miniconda3\Scripts\bidscoiner.exe\__main__.py", line 7, in <module>
  File "C:\Users\miniconda3\lib\site-packages\bidscoin\bidscoiner.py", line 378, in main
    bidscoiner(rawfolder    = args.sourcefolder,
  File "C:\Users\miniconda3\lib\site-packages\bidscoin\bidscoiner.py", line 200, in bidscoiner
    module.bidscoiner_plugin(sesfolder, bidsmap, bidssession)
  File "C:\Users\miniconda3\lib\site-packages\bidscoin\plugins\dcm2niix2bids.py", line 412, in bidscoiner_plugin
    with jsonfile.open('r') as json_fid:
  File "C:\Users\miniconda3\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\miniconda3\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '\\Data\\bids\\sub-001\\ses-001\\anat\\sub-001_ses-001_acq-MPRAGE_run-1_T1w.json'`

**Comment by marcelzwiers** [comment]
The errorcode 3 warning is not really an error and the warning will no longer appear in the upcoming release. Also the next dcm2niix release will deal pigz under windows correctly (https://github.com/rordenlab/dcm2niix/issues/650).

It's a bit unclear to me what exactly you mean with "in all previous cases", but I assume dcm2niix is not found by BIDScoin, hence not producing any nifti or json files, am I right?

**Comment by marcelzwiers** [comment]
You said that in the bidsmap you changed the dcm2niix command to: `C:"Program Files"\dcm2niix\dcm2niix.exe`, but I suppose you miss a `\` there after `C:`, i.e. you should change it to `C:\"Program Files"\dcm2niix\dcm2niix.exe`

**Comment by Sam54000** [comment]
Sorry for being unclear:
Indeed dcm2niix is not found by BIDScoin, which is not producing any nifti or json files.

And yes I omitted the `\` in my comment above but in `C:\Users\miniconda3\Lib\sitepackages\bidscoin\heuristics\bidsmap_dccn.yaml` the path was correctly entered 'C:\"Program Files"\dcm2niix\dcm2niix.exe'

**Comment by marcelzwiers** [comment]
Basically, `command` should be the same what you do when you would run dcm2niix in your windows powershell / command prompt (so you can test the command also directly in the command shell)

**Comment by Sam54000** [comment]
Yes I did try without the `'`. I also changed the path in order to not have a space in it -> `C:\Users\Software\MRIcroGL\Resources\dcm2niix.exe` and entered the command like this in `C:\Users\miniconda3\Lib\sitepackages\bidscoin\heuristics\bidsmap_dccn.yaml`

**Comment by marcelzwiers** [comment]
And can you run dcm2niix directly in your command shell (similar to what I did above)?

**Comment by marcelzwiers** [comment]
I don't understand what is going on with your path but if it works, then it works (but it would be nice to understand it of course, so future users won't have to go through your pain) :-)

I think you just have to wait longer, the progress bar progresses per subject and from your logging output it seems that dcm2niix was still busy converting your dmri data. 

I also noticed you are running the latest development code, which I think is great, but beware that I still work on it and that bugs may have been / can be introduced at some point

**Comment by marcelzwiers** [comment]
Your `Eq_1` MPRage warning should not have happened, and dcm2niix says the following about it:
> _Eq is commonly seen in [CT scans](https://github.com/neurolabusc/dcm_qa_ct). For example, CT scans of the brain often have many slices closely packed near the brain stem and only a few slices spread far apart near the top of the head. Variable between-slice spacing is rarer in MRI, and if you see this from a MRI sequence you should ensure that [all of the acquired slices have been provided to dcm2niix](https://neurostars.org/t/field-mapping-siemens-scanners-dcm2niix-output-2-bids/2075/7). NIfTI assumes all 2D slices that form a 3D stack are equidistant. Therefore, dcm2niix reslices the input data to generate an equidistant volume.

**Comment by Sam54000** [comment]
Yes, I think if someone goes through the same error, the walkaround would to process like I did: add the path to the default path and then enter directly in the GUI the command `dcm2niix` when calling bidsmapper. Indeed I agree this is not a sustainable solution, I would like also to know further what's going on, I will investigate. 

Thank you for the warning I will check that.

And thanks for your help!

**Comment by marcelzwiers** [comment]
I think that after a fresh bidscoin install, if you would have added the dcm2niix path permanently (e.g. by running: `setx path "%path%;C:\Program Files\MRIcroGL\Resources"` -> affects newly started terminals only) it would have worked without doing anything in the GUI?
