### ISSUE TITLE
Bidscoiner could not reade phase encoding direction 

### ISSUE THREAD

**Issue by esthjans** [Donders-Institute/bidscoin#250]
Hello all, 

I was trying to run bidscoiner to convert my MRI scans. I have done this before so I have saved a bidsmap before, and normally i just run bidscoiner raw bids to convert the new files that I have added to the raw folder and this used to work. 

I was trying to do this now but I am encountering several issues: 
bidscoiner raw bids 
INFO | 
INFO | -------------- START BIDScoiner 4.4.0: BIDS 1.10.0 ------------
INFO | >>> bidscoiner sourcefolder=/project/3015092.01/Hyperintense/raw bidsfolder=/project/3015092.01/Hyperintense/bids participant=None force=False bidsmap=bidsmap.yaml
INFO | Reading: /project/3015092.01/Hyperintense/bids/code/bidscoin/bidsmap.yaml
WARNING | BIDScoiner version conflict: /project/3015092.01/Hyperintense/bids/code/bidscoin/bidsmap.yaml was created with version 3.7.4, but this is version 4.4.0
INFO | Checking the bidsmap run-items:
SUCCESS | All run-items in the bidsmap are valid
INFO | ------------------- Subject 1/35 -------------------                                                                                                                                   
INFO | >>> Coining datasources in: /project/3015092.01/Hyperintense/raw/sub-004/ses-04                                                                                                        
VERBOSE | Executing plugin: dcm2niix2bids                                                                                                                                                     
WARNING | Could not read PhaseEncodingDirection from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                   
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
ERROR | --> Skipping unknown run: [DICOM] /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                              
-> Re-run the bidsmapper and delete /project/3015092.01/Hyperintense/bids/sub-004/ses-04 to solve this warning
Traceback (most recent call last):                                                                                                                                                            
  File "/opt/bidscoin/4.4.0/bidscoin/bidscoiner.py", line 329, in <module>
    main()
  File "/opt/bidscoin/4.4.0/bidscoin/bidscoiner.py", line 324, in main
    raise error
  File "/opt/bidscoin/4.4.0/bidscoin/bidscoiner.py", line 320, in main
    bidscoiner(**vars(args))
  File "/opt/bidscoin/4.4.0/bidscoin/bidscoiner.py", line 288, in bidscoiner
    personals = module.bidscoiner_plugin(sesfolder, bidsmap, bidssession)
  File "/opt/bidscoin/lib/python3.10/site-packages/duecredit/collector.py", line 438, in cite_wrapper
    return func(*fargs, **fkwargs)
  File "/home/mrphys/estjan/.bidscoin/4.4.0/plugins/dcm2niix2bids.py", line 265, in bidscoiner_plugin
    bids.bidsprov(bidsses, source)                              # Write out empty provenance logging data
  File "/opt/bidscoin/4.4.0/bidscoin/bids.py", line 2726, in bidsprov
    provdata.loc[str(source)] = [runitem.provenance, runitem.datatype or 'n/a', ', '.join([f"{target.parts[1]+':' if target.parts[0]=='derivatives' else ''}{target.name}" for target in targets])]
AttributeError: 'NoneType' object has no attribute 'provenance'

Bidscoiner fails to read the phase encoding direction from the files. I have tried running other subjects and transferring the dicom files again because I thought the files may be corrupted, but I keep getting this error. 

If I try to run bidsmapper raw bids -n sub-004 -m ses-04 I get loads of the same errors: 
Mapping: /project/3015092.01/Hyperintense/raw/sub-004/ses-04 (subject 1/1)                                                                                                             
VERBOSE | Executing plugin: dcm2niix2bids -> /project/3015092.01/Hyperintense/raw/sub-004/ses-04                                                                                              
WARNING | Could not read PhaseEncodingDirection from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                   
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read PulseSequenceName from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                        
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EffectiveEchoTime from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                        
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EchoPulseSequence from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                        
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EchoPlanarPulseSequence from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                  
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read SeriesType from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                               
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read Radiopharmaceutical from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                      
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read ReconstructionMethod from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                     
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read NumberOfSlices from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                           
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read NumberOfTimeSlices from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                       
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
INFO | Discovered sample: [DICOM] /project/3015092.01/Hyperintense/raw/sub-004/ses-04/SWI_Images-MR-22/1                                                                                      
WARNING | Could not read PhaseEncodingDirection from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/ep2d_MDDW6_IVIM_AP-MR-18/1                                                           
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read PulseSequenceName from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/ep2d_MDDW6_IVIM_AP-MR-18/1                                                                
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EffectiveEchoTime from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/ep2d_MDDW6_IVIM_AP-MR-18/1                                                                
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EchoPulseSequence from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/ep2d_MDDW6_IVIM_AP-MR-18/1                                                                
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)
WARNING | Could not read EchoPlanarPulseSequence from /project/3015092.01/Hyperintense/raw/sub-004/ses-04/ep2d_MDDW6_IVIM_AP-MR-18/1                                                          
Unknown Value Representation 'NONE' in tag (FFFE,E0DD)

.... and way more, i get these errors for every sequence and for every subject and session that I try to run. 

Could this be caused by the discrepancies between version of bidscoiner and bidsmap used? First time I used this program is years ago so the bidsmap is indeed created with a way older version, but I thought this wouldn't be a problem. 

I hope someone can help me, thanks a lot!

**Comment by marcelzwiers** [comment]
Hi, thanks for your report. Yes, using a bidsmap from an older bidscoin version (i.e. your version conflict) can cause unexpected issues (because I don't test/guarantee backward compatibility). I think it may also have to do with the possibility that you are now using a newer version of pydicom? Having said that, I already made fix for your final error `AttributeError: 'NoneType' object has no attribute 'provenance'`. You can try it out by upgrading to the latest development version on Github:
```console
pip install --force-reinstall git+https://github.com/Donders-Institute/bidscoin
```

**Comment by esthjans** [comment]
Hi Marcel, 

Thank you for your quick reply after your vacation!! I tried upgrading bidscoin with the code above, but I get these errors: 

971 $ bidscoiner raw bids 
INFO | 
INFO | -------------- START BIDScoiner 4.5.0: BIDS 1.10.0 ------------
INFO | >>> bidscoiner sourcefolder=/project/3015092.01/Hyperintense/raw bidsfolder=/project/3015092.01/Hyperintense/bids participant=None force=False bidsmap=bidsmap.yaml
INFO | Reading: /project/3015092.01/Hyperintense/bids/code/bidscoin/bidsmap.yaml
WARNING | BIDScoiner version conflict: /project/3015092.01/Hyperintense/bids/code/bidscoin/bidsmap.yaml was created with version 3.7.4, but this is version 4.5.0
INFO | Checking the bidsmap run-items:
SUCCESS | All run-items in the bidsmap are valid
WARNING | The plugins listed in your bidsmap['Options'] did not have a usable `bidscoiner_plugin` function, nothing to do
INFO | -------------- FINISHED! ------------

So it seems like there's something going wrong with the plugins?
