### ISSUE TITLE
participant information

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#253]
Hi Marcel,

I was wondering if it would be possible to add an option in the bidseditor for specifying participant-related values. It’s great that the tool automatically generates a participants.tsv and corresponding JSON file, but it would be really helpful to be able to define variables like sex (and potentially others) directly through the interface.

For instance, the current participants.json includes a "Level" entry for age, which doesn’t quite fit unless we’re categorizing participants into discrete groups like “young” or “old.” A format similar to what’s used in the [neurobagel](https://annotate.neurobagel.org) project might be a good reference.

What do you think?

Best,
Karl

**Comment by marcelzwiers** [comment]
So if I understood you properly, you'd like to be able to specify dynamic values for the participants.tsv file? Something like

```json
participants:
  participant_id: <<filepath:/raw/sub-(.*?)/>>
  session_id: <<filepath:/raw/sub-.*?/ses-(.*?)/>>
  group:
  age: <<PatientAge>>
  sex: <<PatientSex>>
  size: <<PatientSize>>
  weight: <<PatientWeight>>
```
Currently this info is now collected in the plugins, but I guess it may indeed be useful to be able to add to that using the GUI

**Comment by karl-koschutnig** [comment]
Thanks for the quick reply (as always!!)

Yeah, a GUI option would be nice. Indeed, it would be great to have a way to change the corresponding json file. So for example we get the sex from the DCM-Tag and also want to set the levels in the json file. 
That ultimate renders to: 

    "sex": {
        "Description": "sex of the participant as reported by the participant",
        "Levels": {
            "M": "male",
            "F": "female"
        }
    },

**Comment by marcelzwiers** [comment]
I will give it a try to see how it works out. Btw, do you have Presentation logfiles in your dataflow? Because in the upcoming version I added a new feature to convert that to BIDS too (i.e. to a `sub*_events.tsv` file) and I can always use feedback :-)

**Comment by karl-koschutnig** [comment]
Great - thanks a lot!

Yes, we do have some "old" studies that have used neurons. I am happy to help and try it out!
We invested much time in dealing with events files and made a little psychopy module (https://psychopy-bids.readthedocs.io/en/stable/).

**Comment by marcelzwiers** [comment]
I played around a bit with the interface and I can make something to customize the participants.tsv file. The json-sidecar is much harder though, because of its nested structure. Yet, I understood it's the sidecar that you are after, right? Or would you also like to tweak the table?

**Comment by karl-koschutnig** [comment]
I know this is not easy to implement. I really appreciate your effort. 
Have you had the chance to look at the neurobagel approach (link in the first post). There, you "upload" a tsv and can annotate basic stuff. Something like that would be great. 
In my world, it would be perfect to have some basic participants info in the exact same format after coining them. Later, I would tweak the table (but not in the conversion process).

**Comment by marcelzwiers** [comment]
I am still thinking about the best way to implement this, as part of a refactoring. It may take a while...

**Comment by marcelzwiers** [comment]
Ok, I paved the way a bit and adjusted the bidscoin such that the contents of the participant.tsv file can now be specified in the template bidsmap. What I didn't do (yet) is to make this editable in the bidseditor, and to offer a possibility to annotate data in a json sidecar like neurobagel does.

**Comment by karl-koschutnig** [comment]
Thanks a lot!

I just downloaded the latest version and had a first try (under macos - just saying ,-). Bidsmapper worked as expected but the bidscoiner prompted an error regarding the participants file. 

Traceback (most recent call last):                                                                                  
  File "/Users/User/opt/miniconda3/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/Users/User/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 315, in main
    raise error
  File "/Users/User/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 311, in main
    bidscoiner(**vars(args))
  File "/Users/User/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 279, in bidscoiner
    personals = plugin.Interface().personals(bidsmap, datasource)
  File "/Users/User/opt/miniconda3/lib/python3.9/site-packages/bidscoin/plugins/__init__.py", line 65, in personals
    for key, value in bidsmap.dataformat(datasource.dataformat).participant:
ValueError: too many values to unpack (expected 2)

**Comment by marcelzwiers** [comment]
Yes, that could be, because I just committed the patch without that much testing. Did you start from scratch, i.e. with an empty ~/.bidscoin/4.5.0 directory, with an empty bids/code/bidscoin folder (i.e. without a previous study bidsmap), and with the new template bidsbsmap?

**Comment by marcelzwiers** [comment]
Ok, I think I fixed it, can you try again?

**Comment by karl-koschutnig** [comment]
You fixing > me testing ;-)

The error stays the same. Here is what I did. I guess I did something wrong:

- createa new pyhton env (python -m venv bidscoin)
- upgrade pip (/Volumes/data/work/bidscoin/bidscoin/bin/python -m pip install --upgrade pip )
- install bidscoin (pip install "bidscoin[dcm2niix2bids]@git+https://github.com/Donders-Institute/bidscoin"); btw. the command on readthedocs doesn't work on mac os. I had to use ""
- bidsmapper sourcedata . 
returned this:

bidsmapper sourcedata .

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/karlkoschutnig/opt/miniconda3/bin/bidsmapper", line 5, in <module>
    from bidscoin.bidsmapper import main
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidsmapper.py", line 22, in <module>
    from bidscoin.bids import BidsMap
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bids.py", line 13, in <module>
    import pandas as pd
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/karlkoschutnig/opt/miniconda3/lib/python3.9/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found
INFO | 
INFO | -------------- START BIDSmapper ------------
INFO | >>> bidsmapper sourcefolder=/Volumes/data/work/bidscoin/sourcedata bidsfolder=/Volumes/data/work/bidscoin bidsmap=bidsmap.yaml template=/Users/karlkoschutnig/.bidscoin/4.5.0/templates/bidsmap_dccn.yaml plugins=[] subprefix=None sesprefix=None store=False force=False
INFO | No bidsmap file found: /Volumes/data/work/bidscoin/code/bidscoin/bidsmap.yaml
INFO | Reading: /Users/karlkoschutnig/.bidscoin/4.5.0/templates/bidsmap_dccn.yaml
INFO | Checking the bidsmap run-items:
INFO | Missing 'beh' run-item in: bidsmap[Presentation][beh] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'eeg' run-item in: bidsmap[Presentation][eeg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'ieeg' run-item in: bidsmap[Presentation][ieeg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'meg' run-item in: bidsmap[Presentation][meg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'meg' run-item in: bidsmap[Presentation][meg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'meg' run-item in: bidsmap[Presentation][meg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'headshape' run-item in: bidsmap[Presentation][meg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'markers' run-item in: bidsmap[Presentation][meg] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'nirs' run-item in: bidsmap[Presentation][nirs] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'bold' run-item in: bidsmap[Presentation][func] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'cbv' run-item in: bidsmap[Presentation][func] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'sbref' run-item in: bidsmap[Presentation][func] (NB: this may perhaps be fine / a deprecated item)
INFO | Missing 'noRF' run-item in: bidsmap[Presentation][func] (NB: this may perhaps be fine / a deprecated item)
SUCCESS | All datatypes and options in the template bidsmap are valid
INFO | Mapping: /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1 (subject 1/1)                                                                                                              
VERBOSE | Executing plugin: dcm2niix2bids -> /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1                                                                                               
VERBOSE | Ignoring hidden file/folder: .DS_Store                                                                                                                                                          
INFO | Discovered sample: [DICOM] /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/005-func_task-Rest_acq-Fs2-30.0/00001.dcm                                                                
INFO | Discovered sample: [DICOM] /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/007-anat-T1w-2.06/00001.dcm                                                                              
VERBOSE | Executing plugin: events2bids -> /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1                                                                                                 
VERBOSE | Ignoring hidden file/folder: .DS_Store                                                                                                                                                          
INFO | Opening the bidseditor                                                                                                                                                                             
2025-01-15 14:49:49.078 python3[57285:5095316] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-15 14:49:49.078 python3[57285:5095316] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2025-01-15 14:49:53.929 python3[57285:5095316] The class 'NSSavePanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
INFO | Checking the bidsmap run-items:
SUCCESS | All run-items in the bidsmap are valid
INFO | Saving bidsmap in: /Volumes/data/work/bidscoin/code/bidscoin/bidsmap.yaml
INFO | -------------- FINISHED! -------------------
INFO | 
SUCCESS | No BIDScoin errors or warnings were reported
INFO | 
INFO | For the complete log see: /Volumes/data/work/bidscoin/code/bidscoin/bidsmapper.log
NB: That folder may contain privacy sensitive information, e.g. pathnames in logfiles and provenance data samples


Finally the coiner:

INFO | -------------- START BIDScoiner 4.5.0: BIDS 1.10.0 ------------
INFO | >>> bidscoiner sourcefolder=/Volumes/data/work/bidscoin/sourcedata bidsfolder=/Volumes/data/work/bidscoin participant=None force=False bidsmap=bidsmap.yaml
INFO | Creating dataset description file: /Volumes/data/work/bidscoin/dataset_description.json
INFO | Creating a template README file (adjust it to your needs): /Volumes/data/work/bidscoin/README
INFO | Reading: /Volumes/data/work/bidscoin/code/bidscoin/bidsmap.yaml
INFO | Checking the bidsmap run-items:
SUCCESS | All run-items in the bidsmap are valid
INFO | ------------------- Subject 1/1 -------------------                                                                                                                                                
VERBOSE | Ignoring hidden file/folder: .DS_Store                                                                                                                                                          
INFO | >>> Coining dcm2niix2bids datasources in: /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1                                                                                           
VERBOSE | Executing plugin: dcm2niix2bids                                                                                                                                                                 
VERBOSE | Ignoring hidden file/folder: .DS_Store                                                                                                                                                          
INFO | --> Coining: [DICOM] /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/005-func_task-Rest_acq-Fs2-30.0/00001.dcm                                                                      
VERBOSE | Command:                                                                                                                                                                                        
dcm2niix -b y -z y -i n -l n -f "sub-126BPCP021120_ses-1_task-functaskRestacqFs2_bold" -o "/Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/func" "/Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/005-func_task-Rest_acq-Fs2-30.0"
VERBOSE | Output:                                                                                                                                                                                         
Chris Rorden's dcm2niiX version v1.0.20241211  Clang16.0.0 x86-64 (64-bit MacOS)
Found 420 DICOM file(s)
Convert 420 DICOM as /Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/func/sub-126BPCP021120_ses-1_task-functaskRestacqFs2_bold (96x96x60x420)
Conversion required 38.612474 seconds (36.139294 for core code).

INFO | --> Coining: [DICOM] /Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/007-anat-T1w-2.06/00001.dcm                                                                                    
VERBOSE | Command:                                                                                                                                                                                        
dcm2niix -b y -z y -i n -l n -f "sub-126BPCP021120_ses-1_acq-anat_T1w" -o "/Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/anat" "/Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1/007-anat-T1w-2.06"
VERBOSE | Output:                                                                                                                                                                                         
Chris Rorden's dcm2niiX version v1.0.20241211  Clang16.0.0 x86-64 (64-bit MacOS)
Found 1 DICOM file(s)
Convert 1 DICOM as /Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/anat/sub-126BPCP021120_ses-1_acq-anat_T1w (256x256x224x1)
Conversion required 3.036508 seconds (2.993987 for core code).

VERBOSE | Writing acquisition time data to: /Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/sub-126BPCP021120_ses-1_scans.tsv                                                                         
Traceback (most recent call last):                                                                                                                                                                        
  File "/Users/user/opt/miniconda3/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/Users/user/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 315, in main
    raise error
  File "/Users/user/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 311, in main
    bidscoiner(**vars(args))
  File "/Users/user/opt/miniconda3/lib/python3.9/site-packages/bidscoin/bidscoiner.py", line 279, in bidscoiner
    personals = plugin.Interface().personals(bidsmap, datasource)
  File "/Users/user/opt/miniconda3/lib/python3.9/site-packages/bidscoin/plugins/__init__.py", line 65, in personals
    for key, value in bidsmap.dataformat(datasource.dataformat).participant:
ValueError: too many values to unpack (expected 2)

**Comment by marcelzwiers** [comment]
I don't know about your numpy warnings/errors, but I guess they are unrelated to the current issue. I think your installation did not install the latest code (with the path), because your error still shows the old code. That is your line 65 was:

```python
for key, value in bidsmap.dataformat(datasource.dataformat).participant:
```

But I [patched](https://github.com/Donders-Institute/bidscoin/commit/740c00a1da73abd99b5d273c15861a97d373b072) it to:

```python
for key, value in bidsmap.dataformat(datasource.dataformat).participant.items():
```

**Comment by karl-koschutnig** [comment]
Thanks!
I tried multiple installations - nothing really worked. I finally cloned your repo and changed the line manually. Now it works!


VERBOSE | Writing acquisition time data to: /Volumes/data/work/bidscoin/sub-126BPCP021120/ses-1/sub-126BPCP021120_ses-1_scans.tsv                             
VERBOSE | Writing sub-126BPCP021120 subject data to: /Volumes/data/work/bidscoin/participants.tsv                                                             
VERBOSE | Writing subject meta data to: /Volumes/data/work/bidscoin/participants.json                                                                         
VERBOSE | Ignoring hidden file/folder: .DS_Store                                                                                                              
INFO | >>> No events2bids datasources found in '/Volumes/data/work/bidscoin/sourcedata/sub-126BPCP021120/ses-1'                                               
INFO | -------------- FINISHED! ------------                                                                                                                  
INFO | 
SUCCESS | No BIDScoin errors or warnings were reported
INFO | 
INFO | For the complete log see: /Volumes/data/work/bidscoin/code/bidscoin/bidscoiner.log
NB: That folder may contain privacy sensitive information, e.g. pathnames in logfiles and provenance data samples

**Comment by marcelzwiers** [comment]
Sorry to hear that, I guess you also tried the `pip --force-reinstall` option? That helped me out in the past...

**Comment by marcelzwiers** [comment]
I guess it's a bug (or missing functionality) in pip, it only looks at the package version number when installing. So if you install from github, it doesn't look at the latest commits, and nothing will be updated if the version number (here `4.5.0`) didn't change (which it didn't). Hence the force-reinstall

**Comment by marcelzwiers** [comment]
FYI, I've taken things another step forward and added the sidecar meta data to the (template) bidsmap. Again, I still need to develop and perform more tests, so not everything may work yet. In any, if you want to give it a go, install with the `force-reinstall` option and also, since the default templates have changed, remove your `bidscoin/4.5.0` config folder (e.g. by running `bidscoin -r`).

The next step is to make it all editable within the bidseditor...

**Comment by marcelzwiers** [comment]
The template bidsmap now looks like this snippet:

```yaml
DICOM:
  participant:                      # Attributes or properties to populate the participants table/tsv-file
    participant_id: &participant_id
      value: <<filepath:/sub-(.*?)/>>           # This filesystem property extracts the subject label from the source directory. NB: Any property or attribute can be used as subject-label, e.g. <PatientID>
      meta:
        Description: The unique participant identifier of the form sub-<label>, matching a participant entity found in the dataset
    session_id: &session_id
      value: <<filepath:/sub-.*?/ses-(.*?)/>>   # This filesystem property extracts the session label from the source directory. NB: Any property or attribute can be used as session-label, e.g. <StudyID>
      meta:
        Description: The session identifier of the form ses-<label>, matching a session found in the dataset
    age: &age
      value: <<PatientAge>>
      meta:
        Description: Age of the participant
        Units: year
    sex: &sex
      value: <<PatientSex>>
      meta:
        Description: Sex of the participant
        Levels:
          M: male
          F: female
          O: other
    height: &height
      value: <<PatientSize>>
      meta:
        Description: Height of the participant
        Units: meter
    weight: &weight
      value: <<PatientWeight>>
      meta:
        Description: Weight of the participant
        Units: kilogram
```

**Comment by marcelzwiers** [comment]
Here's a draft version of the new GUI, feedback is welcome :-)

![Image](https://github.com/user-attachments/assets/0dd04d8e-a921-461f-96bd-7925b511c15a)

**Comment by karl-koschutnig** [comment]
Awesome!

This is really great and a big help for us. 

- The bidscoin.yaml now includes the dicom data (as in your snipper): check!
- I started the bidsmapper with your template (../bidscoin-master/tests/test_data/bidsmap.yaml) and got an error. Then find / replaced (nrfiles: '' with nrfiles null) and the error disappeared. 
- Unfortunately, the GUI option (participant data) doesn't show? 
- participants json and tsv look perfect!!

Thanks again! Really appreciate your work

**Comment by marcelzwiers** [comment]
> I started the bidsmapper with your template (../bidscoin-master/tests/test_data/bidsmap.yaml) and got an error. Then find / replaced (nrfiles: '' with nrfiles null) and the error disappeared.

That's not a template, but what was the error?

> Unfortunately, the GUI option (participant data) doesn't show?

That's because I didn't push my commits yet, I did that just now :-) Note that this is still experimental and unfinished (the most obvious function that is not yet implemented: add/remove rows in the bidseditor `Participant data` table

**Comment by karl-koschutnig** [comment]
My mistake - I tried to use your template because I thought there was a connection with the GUI?!

Here is the warning (not an error;-)
WARNING | Invalid template bidsmap:
'' is not of type 'integer', 'null'

Failed validating 'type' in schema['additionalProperties']['additionalProperties']['items']['properties']['properties']['properties']['nrfiles']:
    {'type': ['integer', 'null']}

On instance['DICOM']['func'][3]['properties']['nrfiles']:
    ''


Looking forward to using the GUI. If you need some more testing - let me know. 
2 final things: 1) MAybe you could make a new branch on github 2) Maybe we should discuss things like this via email not vie github? This would be karl.koschutnig@uni-graz.at

**Comment by marcelzwiers** [comment]
It works for me, so I would be grateful if you give it a try as well. A new branch is not needed anymore because I plan to release the current version (after I've done more testing). I'm fine with communicating via GitHub, to give other people some insights too, and allow them to chip in

**Comment by marcelzwiers** [comment]
I believe that the functionality is implemented and works well. If not so for you, or if you have additional ideas, then please re-open this issue. Thanks for your helpful feedback!

**Comment by marcelzwiers** [comment]
So I went ahead and released the new version, hope it works well for you (and before using it, don't forget to run `bidscoin -r`)

**Comment by marcelzwiers** [comment]
FYI, the latest BIDScoin code now supports converting PsychoPy csv-files into BIDS. I know you invested heavily in making a very nice BIDS-plugin for PsychoPy, but I thought that perhaps you may still sometimes have data that was collected without the plugin (I see the new code as complementary to your plugin). I must say that I myself know very little about PsychoPy, I just made conversion code that may well lack features or misses out on use cases. If you are interested to try it out, then install the latest code and have a look at the (at the moment very short) docs:

https://bidscoin.readthedocs.io/en/latest/workflow.html#stimulus-events
