### ISSUE TITLE
File writing error without clear error message

### ISSUE THREAD

**Issue by TimVanMourik** [Donders-Institute/bidscoin#47]
I just wanted to try things out and tried to run:
```
bidscoiner.py -b /opt/bidscoin/2.3/heuristics/bidsmap_template.yaml  [sourcefolder] [bidsfolder]
```
I had not previsouly run the bidsmapper and link to a template map that has not been trained on my data, so indeed gives an error message:
```
2019-09-20 11:17:43 - bidscoin - INFO Writing acquisition time data to: /project/3015003.04/Studies/DSC_AttentionStudy/BasePipeline/Subject11/Scans/Functional/NifTI/sub-011/sub-011_scans.tsv
Traceback (most recent call last):
  File "/opt/bidscoin/dev/bidscoin/bidscoiner.py", line 599, in <module>
    sesprefix    = args.sesprefix)
  File "/opt/bidscoin/dev/bidscoin/bidscoiner.py", line 516, in bidscoiner
    coin_dicom(session, bidsmap, bidsfolder, personals, subprefix, sesprefix)
  File "/opt/bidscoin/dev/bidscoin/bidscoiner.py", line 249, in coin_dicom
    bidsname    = bids.get_bidsname(subid, sesid, 'fmap', fieldmap)
  File "/opt/bidscoin/dev/bidscoin/bids.py", line 1045, in get_bidsname
    subid, sesid = get_subid_sesid(run['provenance'], subid, sesid, subprefix, sesprefix)
  File "/opt/bidscoin/dev/bidscoin/bids.py", line 1008, in get_subid_sesid
    dicompath = os.path.dirname(dicomfile)
  File "/opt/bidscoin/lib/python3.6/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The fact that it yields an error is unsurprising, yet it might be nice to give a clearer error of what's going wrong exaclty. At this moment I can't quite see if this might turn up in different circumstances where the tool is used correctly but the data is wrong.

**Comment by marcelzwiers** [comment]
The user input error is now handled more gracefully (i.e. no crash): 6b73110da9fc396179c46ce7a3c9e7c5983ccedc
