### ISSUE TITLE
datutil.parser empty in ADNI data

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#58]
I'm converting a lot of ADNI data, which is really variable in terms of sequences/acquisitions (Siemens, Phillips, GE). Getting this error quite a lot:

```
2020-09-25 09:00:03 - bidscoin - INFO ------------------- Subject 62/713 -------------------
2020-09-25 09:00:03 - bidscoin - INFO Coining session: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01
2020-09-25 09:00:16 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE
2020-09-25 09:00:16 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE"
2020-09-25 09:00:22 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 212 DICOM file(s)
Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 3.40928:0
 Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 211 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa.nii"
Conversion required 6.110341 seconds (0.639448 for core code).

Traceback (most recent call last):
  File "/data/home/uqtshaw/anaconda3/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 623, in main
    sesprefix    = args.sesprefix)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 539, in bidscoiner
    coin_data2bids(dataformat, session, bidsmap, bidsfolder, personals, subprefix, sesprefix)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 243, in coin_data2bids
    acq_time = dateutil.parser.parse(data['AcquisitionTime'])
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 652, in parse
    raise ParserError("String does not contain a date: %s", timestr)
dateutil.parser._parser.ParserError: String does not contain a date:
```
Is there a way that I can fix this? 
Thanks!

**Comment by marcelzwiers** [comment]
I made a quick fix, or at least not make it crash (which should never happen of course). Can you test it using e.g. `pip install git+https://github.com/Donders-Institute/bidscoin`? I will do a new point release if this works for you. I suspect the reason for the crash was that there is no `AcquisitionTime` field in the DICOM header or no `exam_date` in the PAR-file, perhaps due to (a bit too) aggressive anonymization?

**Comment by thomshaw92** [comment]
Still no luck I'm afraid:
```
2020-09-25 23:17:06 - bidscoin - INFO ------------------- Subject 62/713 -------------------
2020-09-25 23:17:06 - bidscoin - INFO Coining session: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01
2020-09-25 23:17:19 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE
2020-09-25 23:17:19 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE"
2020-09-25 23:17:26 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 212 DICOM file(s)
Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 3.40928:0
 Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 211 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa.nii"
Conversion required 7.075567 seconds (0.559534 for core code).

Traceback (most recent call last):
  File "/data/home/uqtshaw/anaconda3/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 623, in main
    sesprefix    = args.sesprefix)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 539, in bidscoiner
    coin_data2bids(dataformat, session, bidsmap, bidsfolder, personals, subprefix, sesprefix)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/bidscoin/bidscoiner.py", line 243, in coin_data2bids
    acq_time = dateutil.parser.parse(data['AcquisitionTime'])
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/data/home/uqtshaw/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 652, in parse
    raise ParserError("String does not contain a date: %s", timestr)
dateutil.parser._parser.ParserError: String does not contain a date:
```

**Comment by marcelzwiers** [comment]
@thomshaw92 Ok, I put a (bit ugly) `try` statement in there, that should stop this crash at least :-)

**Comment by thomshaw92** [comment]
I agree, aggressive anonymization. I think there may be some issues with this (and many other) subjects in these data. But it worked! Thank you!
```
2020-09-26 09:35:42 - bidscoin - INFO ------------------- Subject 62/713 -------------------
2020-09-26 09:35:42 - bidscoin - INFO Coining session: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01
2020-09-26 09:35:55 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE
2020-09-26 09:35:55 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE"
2020-09-26 09:36:00 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 212 DICOM file(s)
Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 3.40928:0
 Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 211 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa.nii"
Conversion required 4.733461 seconds (0.544880 for core code).

2020-09-26 09:36:00 - bidscoin - WARNING Could not parse the acquisition time from: '' in /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/MPRAGE/ADNI_006_S_4485_MR_Sagittal_3D_Accelerated_MPRAGE_br_raw_20180925135407568_1_S729784_I1051710.dcm
2020-09-26 09:36:03 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/hippo_scan
2020-09-26 09:36:03 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-01_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/hippo_scan"
2020-09-26 09:36:05 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 31 DICOM file(s)
Philips Scaling Values RS:RI:SS = 9.5243:0:0.0492767 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w (448x448x30x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 9.5243:0
 Philips Scaling Values RS:RI:SS = 9.5243:0:0.0492767 (see PMC3998685)
Convert 30 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2wa (448x448x30x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/anat/sub-006S4485_ses-01_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2wa.nii"
Conversion required 1.418825 seconds (0.144369 for core code).

2020-09-26 09:36:05 - bidscoin - WARNING Could not parse the acquisition time from: '' in /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-01/hippo_scan/ADNI_006_S_4485_MR_HighResHippo_Scan__Oblique_-_perpendicular_to_hippocampal_tail_br_raw_20180925135524327_1_S729790_I1051716.dcm
2020-09-26 09:36:05 - bidscoin - INFO Writing acquisition time data to: /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-01/sub-006S4485_ses-01_scans.tsv
2020-09-26 09:36:05 - bidscoin - INFO Coining session: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02
2020-09-26 09:36:17 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/MPRAGE
2020-09-26 09:36:17 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-02_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/MPRAGE"
2020-09-26 09:36:22 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 212 DICOM file(s)
Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 3.40928:0
 Philips Scaling Values RS:RI:SS = 3.40928:0:0.00323077 (see PMC3998685)
Convert 211 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa (256x256x211x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-Sagittal3DAcceleratedMPRAGE_run-1_T1wa.nii"
Conversion required 5.092845 seconds (0.554319 for core code).

2020-09-26 09:36:23 - bidscoin - WARNING Could not parse the acquisition time from: '' in /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/MPRAGE/ADNI_006_S_4485_MR_Sagittal_3D_Accelerated_MPRAGE_br_raw_20180925135407568_1_S729784_I1051710.dcm
2020-09-26 09:36:26 - bidscoin - INFO Processing: /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/hippo_scan
2020-09-26 09:36:26 - bidscoin - INFO Running: PATH=/data/lfs2/uqtshaw/tools/dcm2niix/build/bin:$PATH;dcm2niix -b y -z y -i n -f "sub-006S4485_ses-02_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w" -o "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat" "/90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/hippo_scan"
2020-09-26 09:36:27 - bidscoin - INFO Output:
Chris Rorden's dcm2niiX version v1.0.20200331  GCC5.4.0 (64-bit Linux)
Found 31 DICOM file(s)
Philips Scaling Values RS:RI:SS = 9.5243:0:0.0492767 (see PMC3998685)
Convert 1 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w (448x448x30x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2w.nii"
Slices not stacked: dimensions or bit-depth varies
Using RWVSlope:RWVIntercept = 9.5243:0
 Philips Scaling Values RS:RI:SS = 9.5243:0:0.0492767 (see PMC3998685)
Convert 30 DICOM as /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2wa (448x448x30x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/anat/sub-006S4485_ses-02_acq-HighResHippoScanObliqueperpendiculartohippocampaltail_run-1_T2wa.nii"
Conversion required 1.367182 seconds (0.141297 for core code).

2020-09-26 09:36:28 - bidscoin - WARNING Could not parse the acquisition time from: '' in /90days/uqtshaw/ADNI_DATA/ADNI_FILTERED/sub-006_S_4485/ses-02/hippo_scan/ADNI_006_S_4485_MR_HighResHippo_Scan__Oblique_-_perpendicular_to_hippocampal_tail_br_raw_20180925135524327_1_S729790_I1051716.dcm
2020-09-26 09:36:28 - bidscoin - INFO Writing acquisition time data to: /90days/uqtshaw/ADNI_DATA/bids/sub-006S4485/ses-02/sub-006S4485_ses-02_scans.tsv
```
